/**
 * Project Euler - Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 *
 * http://projecteuler.net/problem=2
 */

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  unsigned int current;
  unsigned int n1 = 1;
  unsigned int n2 = 1;
  unsigned int sum = 0;
  unsigned int max = 4000000; // 4,000,000 is the problem's given maximum value

  if (argc > 1) {
    max = atoi(argv[1]);
  }

  while (current < max) {
    current = n1 + n2;
    n2 = n1;
    n1 = current;

    if (current % 2 == 0 && current < max) {
      sum += current;
    }
  }

  printf("Sum Total Is: %d\n", sum);

  return 0;
}
